version: "3.9"

networks:
  dsp_net_R00226564:
    name: dsp_net_R00226564
    driver: bridge

services:
  worker-service:
    container_name: worker-service
    hostname: worker
    build:
      context: ..
      dockerfile: worker/Dockerfile
    networks:
      - dsp_net_R00226564

  gateway-service:
    container_name: gateway-service
    hostname: gateway
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    depends_on:
      - worker-service
    ports:
      - "5050:5050"
    networks:
      - dsp_net_R00226564
